- name: "Uninstall other scanning packages: {{ packages_to_uninstall }}"
  ansible.builtin.package:
    name: "{{ packages_to_uninstall }}"
    state: absent
  vars:
    packages_to_uninstall:
      - skanlite
      - gscan2pdf
  become: true
  become_user: root

